### ISSUE TITLE
FontTools docs link is incorrect (and out-of-date)

### ISSUE THREAD

**Issue by n8willis** [lynneyun/Tutorials#3]
The link on "fontTools Python library" is pointing to the wrong place. The project's official docs are at https://fonttools.readthedocs.io/en/latest/ ... the present link is someone's third-party, personal duplicate. It's not official, also not up to date, and several of its internal links break — my guess is that it was bulk-generated from the original docs repo. Anyway, updating the link to the authoritative source would benefit lots and lots of readers!

**Comment by lynneyun** [comment]
Fixed, thank you for the suggestion @n8willis .

https://github.com/lynneyun/Tutorials/commit/7a095f27f2bb59d3053cc346cc0a945618c20754#diff-525e3d9283a9c51d8ff948bf38080d1bb35f3b7c31f44eaed4e9fa9593a8155e
